### ISSUE TITLE
Allow customizing `spring-merge-dependabot-pr.yml` merge strategy

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-io/spring-github-workflows#6]
Some projects might want to pass `--rebase` or even not opt for `--squash`. 

1. `squash` and `rebase` boolean inputs could be added to the workflow. 
2. an option to pass the argument as a whole can be a possibility too, like `merge-arguments: '--rebase --squash`

https://github.com/spring-io/spring-github-workflows/blob/460018c198950730359ed81ac796079467b851aa/.github/workflows/spring-merge-dependabot-pr.yml#L75

**Comment by artembilan** [comment]
Sure! 

The `merge-arguments` optional input sounds good.

Feel free to contribute!

Thanks

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-io/spring-github-workflows/pull/7
